import type {
  Vessel,
  Fleet,
  User,
  Equipment,
  WorkOrder,
  CIIData,
  ETSData,
  PortCongestion,
  KnowledgeDocument,
  SireDocument,
  SireFinding,
  Notification,
  MaintenanceAlert,
  VoyageHistoryRecord,
  PortCall,
  SireChapterScore,
} from './types'

// ─── Vessels ──────────────────────────────────────────────────────────────────

export const MOCK_VESSELS: Vessel[] = [
  {
    id: 'v1',
    name: 'MV Merdeka Spirit',
    imo: '9876543',
    type: 'tanker',
    flag: 'Malaysia',
    yearBuilt: 2018,
    grossTonnage: 28500,
    deadweightTonnage: 47000,
    status: 'underway',
    position: { lat: 4.2105, lng: 108.9758, heading: 245, speed: 12.4, timestamp: new Date().toISOString() },
    fleetId: 'f1',
    ciiRating: 'B',
    fuelEfficiencyScore: 82,
  },
  {
    id: 'v2',
    name: 'MT Kerteh Venture',
    imo: '9765432',
    type: 'tanker',
    flag: 'Malaysia',
    yearBuilt: 2014,
    grossTonnage: 31200,
    deadweightTonnage: 52000,
    status: 'at_anchor',
    position: { lat: 25.354, lng: 56.36, heading: 0, speed: 0, timestamp: new Date().toISOString() },
    fleetId: 'f1',
    ciiRating: 'D',
    fuelEfficiencyScore: 61,
  },
  {
    id: 'v3',
    name: 'OSV Tenaga Satu',
    imo: '9654321',
    type: 'osv',
    flag: 'Malaysia',
    yearBuilt: 2019,
    grossTonnage: 4800,
    deadweightTonnage: 3200,
    status: 'in_port',
    position: { lat: 25.347, lng: 56.342, heading: 90, speed: 0, timestamp: new Date().toISOString() },
    fleetId: 'f1',
    ciiRating: 'C',
    fuelEfficiencyScore: 74,
  },
]

export const MOCK_FLEET: Fleet = {
  id: 'f1',
  name: 'PETRONAS Marine Fleet',
  company: 'PETRONAS',
  vessels: MOCK_VESSELS,
  totalVessels: 3,
}

// ─── User ─────────────────────────────────────────────────────────────────────

export const MOCK_USER: User = {
  id: 'u1',
  name: 'Ahmad Razali',
  email: 'demo@petronas.com',
  role: 'fleet_manager',
  company: 'PETRONAS',
  fleetId: 'f1',
}

// ─── Notifications ────────────────────────────────────────────────────────────

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    severity: 'critical',
    title: 'Turbocharger Bearing Anomaly',
    message: 'Turbocharger bearing anomaly detected on MV Merdeka Spirit — 4 days to potential failure',
    vesselId: 'v1',
    vesselName: 'MV Merdeka Spirit',
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    read: false,
    link: '/maintenance',
  },
  {
    id: 'n2',
    severity: 'critical',
    title: 'CII Rating at Risk',
    message: 'MT Kerteh Venture CII rating at D — risk of regulatory action in Q1 2025',
    vesselId: 'v2',
    vesselName: 'MT Kerteh Venture',
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    read: false,
    link: '/compliance',
  },
  {
    id: 'n3',
    severity: 'warning',
    title: 'Demurrage Risk',
    message: 'OSV Tenaga Satu approaching demurrage threshold at Port Fujairah — 6 hours laytime remaining',
    vesselId: 'v3',
    vesselName: 'OSV Tenaga Satu',
    createdAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    read: false,
    link: '/ports',
  },
  {
    id: 'n4',
    severity: 'success',
    title: 'Route Optimization Saved',
    message: 'AI route saved $18,450 on MV Merdeka Spirit voyage to Singapore',
    vesselId: 'v1',
    vesselName: 'MV Merdeka Spirit',
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    read: true,
    link: '/voyage',
  },
  {
    id: 'n5',
    severity: 'info',
    title: 'SIRE Inspection Scheduled',
    message: 'MT Kerteh Venture SIRE inspection scheduled for 15 Nov 2024 at Fujairah',
    vesselId: 'v2',
    vesselName: 'MT Kerteh Venture',
    createdAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    read: true,
    link: '/sire',
  },
]

// ─── Equipment ────────────────────────────────────────────────────────────────

export const MOCK_EQUIPMENT: Equipment[] = [
  {
    id: 'e1',
    name: 'Main Engine',
    type: 'propulsion',
    vesselId: 'v1',
    healthScore: 85,
    status: 'healthy',
    lastMaintenance: '2024-09-15',
    nextMaintenance: '2025-03-15',
    runningHours: 12450,
    manufacturer: 'MAN B&W',
    model: '6S50MC-C8',
    serialNumber: 'ME-2018-001',
    sensors: [
      { id: 's1', name: 'Exhaust Temp Cyl.1', unit: '°C', currentValue: 385, normalRange: [350, 420], warningRange: [420, 450] },
      { id: 's2', name: 'Scavenge Air Pressure', unit: 'bar', currentValue: 2.8, normalRange: [2.5, 3.2], warningRange: [3.2, 3.5] },
      { id: 's3', name: 'Lube Oil Pressure', unit: 'bar', currentValue: 4.2, normalRange: [3.8, 5.0], warningRange: [3.5, 3.8] },
    ],
  },
  {
    id: 'e2',
    name: 'Turbocharger #1',
    type: 'turbocharger',
    vesselId: 'v1',
    healthScore: 62,
    status: 'warning',
    lastMaintenance: '2024-05-20',
    nextMaintenance: '2024-11-20',
    runningHours: 12450,
    manufacturer: 'ABB',
    model: 'TPS57-E',
    serialNumber: 'TC-2018-001',
    sensors: [
      { id: 's4', name: 'Bearing Temperature', unit: '°C', currentValue: 142, normalRange: [80, 130], warningRange: [130, 150] },
      { id: 's5', name: 'RPM', unit: 'rpm', currentValue: 8450, normalRange: [8000, 9000], warningRange: [9000, 9500] },
      { id: 's6', name: 'Vibration', unit: 'mm/s', currentValue: 8.2, normalRange: [0, 6], warningRange: [6, 9] },
    ],
  },
  {
    id: 'e3',
    name: 'Auxiliary Engine #1',
    type: 'auxiliary',
    vesselId: 'v1',
    healthScore: 91,
    status: 'healthy',
    lastMaintenance: '2024-10-01',
    nextMaintenance: '2025-04-01',
    runningHours: 8200,
    manufacturer: 'Wärtsilä',
    model: '6L20',
    serialNumber: 'AE-2018-001',
    sensors: [
      { id: 's7', name: 'Exhaust Temp', unit: '°C', currentValue: 340, normalRange: [300, 380], warningRange: [380, 420] },
      { id: 's8', name: 'Coolant Temp', unit: '°C', currentValue: 78, normalRange: [70, 85], warningRange: [85, 95] },
    ],
  },
  {
    id: 'e4',
    name: 'Cargo Pump #1',
    type: 'pump',
    vesselId: 'v1',
    healthScore: 78,
    status: 'healthy',
    lastMaintenance: '2024-08-10',
    nextMaintenance: '2025-02-10',
    runningHours: 3400,
    manufacturer: 'Framo',
    model: 'S200',
    serialNumber: 'CP-2018-001',
    sensors: [
      { id: 's9', name: 'Flow Rate', unit: 'm³/h', currentValue: 420, normalRange: [380, 480], warningRange: [350, 380] },
      { id: 's10', name: 'Pressure', unit: 'bar', currentValue: 12.5, normalRange: [10, 15], warningRange: [15, 18] },
    ],
  },
  {
    id: 'e5',
    name: 'Main Engine',
    type: 'propulsion',
    vesselId: 'v2',
    healthScore: 44,
    status: 'critical',
    lastMaintenance: '2024-04-10',
    nextMaintenance: '2024-10-10',
    runningHours: 18900,
    manufacturer: 'MAN B&W',
    model: '7S60MC-C',
    serialNumber: 'ME-2014-001',
    sensors: [
      { id: 's11', name: 'Exhaust Temp Cyl.1', unit: '°C', currentValue: 460, normalRange: [350, 420], warningRange: [420, 450] },
      { id: 's12', name: 'Lube Oil Pressure', unit: 'bar', currentValue: 3.2, normalRange: [3.8, 5.0], warningRange: [3.5, 3.8] },
    ],
  },
  {
    id: 'e6',
    name: 'Purifier #1',
    type: 'separator',
    vesselId: 'v2',
    healthScore: 55,
    status: 'warning',
    lastMaintenance: '2024-06-15',
    nextMaintenance: '2024-12-15',
    runningHours: 6200,
    manufacturer: 'Alfa Laval',
    model: 'MAPX 207',
    serialNumber: 'PU-2014-001',
    sensors: [
      { id: 's13', name: 'Bowl Speed', unit: 'rpm', currentValue: 7200, normalRange: [7400, 7600], warningRange: [7200, 7400] },
      { id: 's14', name: 'Vibration', unit: 'mm/s', currentValue: 7.8, normalRange: [0, 5], warningRange: [5, 8] },
    ],
  },
]

export const MOCK_ALERTS: MaintenanceAlert[] = [
  {
    id: 'a1',
    equipmentId: 'e2',
    equipmentName: 'Turbocharger #1',
    vesselId: 'v1',
    severity: 'warning',
    message: 'Bearing temperature trending upward — 142°C (limit: 150°C). Vibration elevated at 8.2 mm/s.',
    detectedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    daysToFailure: 4,
    aiAnalysis: 'Bearing wear pattern consistent with inadequate lubrication. Recommend immediate lube oil analysis and bearing inspection at next port call.',
  },
  {
    id: 'a2',
    equipmentId: 'e5',
    equipmentName: 'Main Engine',
    vesselId: 'v2',
    severity: 'critical',
    message: 'Multiple cylinder exhaust temperatures elevated. Lube oil pressure below minimum threshold.',
    detectedAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    daysToFailure: 2,
  },
]

// ─── Work Orders ──────────────────────────────────────────────────────────────

export const MOCK_WORK_ORDERS: WorkOrder[] = [
  {
    id: 'w1',
    equipmentId: 'e2',
    equipmentName: 'Turbocharger #1',
    vesselId: 'v1',
    title: 'Turbocharger Bearing Inspection',
    description: 'Inspect and replace turbocharger bearings due to elevated temperature and vibration readings',
    status: 'open',
    priority: 'high',
    type: 'corrective',
    assignedTo: 'Chief Engineer Ibrahim',
    plannedDate: '2024-11-20',
    estimatedHours: 8,
    partsRequired: ['TC Bearing Set ABB TPS57', 'Lube Oil 10L'],
  },
  {
    id: 'w2',
    equipmentId: 'e3',
    equipmentName: 'Auxiliary Engine #1',
    vesselId: 'v1',
    title: '500-hour Preventive Maintenance',
    description: 'Scheduled 500h service: cylinder head inspection, fuel injector calibration, filter replacement',
    status: 'in_progress',
    priority: 'medium',
    type: 'preventive',
    assignedTo: '2nd Engineer Hassan',
    plannedDate: '2024-11-25',
    estimatedHours: 12,
    partsRequired: ['Fuel Injector Set', 'Lube Oil Filter', 'Fuel Filter'],
  },
  {
    id: 'w3',
    equipmentId: 'e4',
    equipmentName: 'Cargo Pump #1',
    vesselId: 'v1',
    title: 'Cargo Pump Seal Replacement',
    description: 'Replace mechanical seal due to minor leakage detected during last cargo operation',
    status: 'completed',
    priority: 'medium',
    type: 'corrective',
    assignedTo: '3rd Engineer Siti',
    plannedDate: '2024-11-10',
    completedDate: '2024-11-10',
    estimatedHours: 4,
    partsRequired: ['Mechanical Seal Kit Framo S200'],
  },
  {
    id: 'w4',
    equipmentId: 'e5',
    equipmentName: 'Main Engine',
    vesselId: 'v2',
    title: 'Emergency: Lube Oil System Investigation',
    description: 'Urgent investigation of lube oil pressure drop. Check pump, filters, and relief valves.',
    status: 'open',
    priority: 'critical',
    type: 'corrective',
    assignedTo: 'Chief Engineer Ravi',
    plannedDate: '2024-11-15',
    estimatedHours: 6,
  },
  {
    id: 'w5',
    equipmentId: 'e6',
    equipmentName: 'Purifier #1',
    vesselId: 'v2',
    title: 'Purifier Bowl Cleaning and Inspection',
    description: 'Disassemble, clean and inspect purifier bowl due to vibration and reduced separation efficiency',
    status: 'verified',
    priority: 'high',
    type: 'corrective',
    assignedTo: '2nd Engineer Muthu',
    plannedDate: '2024-11-05',
    completedDate: '2024-11-06',
    estimatedHours: 6,
  },
]

// ─── CII Data ─────────────────────────────────────────────────────────────────

export const MOCK_CII_DATA: Record<string, CIIData> = {
  v1: {
    vesselId: 'v1',
    year: 2024,
    currentRating: 'B',
    currentValue: 7.82,
    requiredValue: 8.5,
    trajectory: [
      { month: 'Jan', actual: 8.1, required: 8.8 },
      { month: 'Feb', actual: 7.9, required: 8.7 },
      { month: 'Mar', actual: 8.3, required: 8.6 },
      { month: 'Apr', actual: 7.6, required: 8.5 },
      { month: 'May', actual: 7.4, required: 8.4 },
      { month: 'Jun', actual: 7.8, required: 8.3 },
      { month: 'Jul', actual: 8.0, required: 8.2 },
      { month: 'Aug', actual: 7.9, required: 8.1 },
      { month: 'Sep', actual: 7.5, required: 8.0 },
      { month: 'Oct', actual: 7.82, required: 7.9 },
    ],
    daysToRatingChange: 95,
    projectedYearEnd: 'B',
  },
  v2: {
    vesselId: 'v2',
    year: 2024,
    currentRating: 'D',
    currentValue: 11.24,
    requiredValue: 8.5,
    trajectory: [
      { month: 'Jan', actual: 10.2, required: 8.8 },
      { month: 'Feb', actual: 10.5, required: 8.7 },
      { month: 'Mar', actual: 11.1, required: 8.6 },
      { month: 'Apr', actual: 10.8, required: 8.5 },
      { month: 'May', actual: 11.3, required: 8.4 },
      { month: 'Jun', actual: 11.0, required: 8.3 },
      { month: 'Jul', actual: 11.5, required: 8.2 },
      { month: 'Aug', actual: 11.2, required: 8.1 },
      { month: 'Sep', actual: 11.4, required: 8.0 },
      { month: 'Oct', actual: 11.24, required: 7.9 },
    ],
    daysToRatingChange: 45,
    projectedYearEnd: 'E',
  },
  v3: {
    vesselId: 'v3',
    year: 2024,
    currentRating: 'C',
    currentValue: 9.15,
    requiredValue: 8.5,
    trajectory: [
      { month: 'Jan', actual: 9.4, required: 8.8 },
      { month: 'Feb', actual: 9.1, required: 8.7 },
      { month: 'Mar', actual: 9.3, required: 8.6 },
      { month: 'Apr', actual: 9.0, required: 8.5 },
      { month: 'May', actual: 9.2, required: 8.4 },
      { month: 'Jun', actual: 8.9, required: 8.3 },
      { month: 'Jul', actual: 9.1, required: 8.2 },
      { month: 'Aug', actual: 9.3, required: 8.1 },
      { month: 'Sep', actual: 9.0, required: 8.0 },
      { month: 'Oct', actual: 9.15, required: 7.9 },
    ],
    daysToRatingChange: 62,
    projectedYearEnd: 'C',
  },
}

// ─── ETS Data ─────────────────────────────────────────────────────────────────

export const MOCK_ETS_DATA: Record<string, ETSData> = {
  v1: {
    vesselId: 'v1',
    year: 2024,
    totalCO2: 8420,
    annualEstimate: 10100,
    eurCost: 842000,
    allowancesPurchased: 7500,
    allowancesRequired: 10100,
    projectedYearEndCost: 1010000,
    monthlyData: [
      { month: 'Jan', co2: 920, cost: 92000 },
      { month: 'Feb', co2: 850, cost: 85000 },
      { month: 'Mar', co2: 890, cost: 89000 },
      { month: 'Apr', co2: 810, cost: 81000 },
      { month: 'May', co2: 870, cost: 87000 },
      { month: 'Jun', co2: 840, cost: 84000 },
      { month: 'Jul', co2: 760, cost: 76000 },
      { month: 'Aug', co2: 800, cost: 80000 },
      { month: 'Sep', co2: 830, cost: 83000 },
      { month: 'Oct', co2: 850, cost: 85000 },
    ],
  },
  v2: {
    vesselId: 'v2',
    year: 2024,
    totalCO2: 12650,
    annualEstimate: 15200,
    eurCost: 1265000,
    allowancesPurchased: 8000,
    allowancesRequired: 15200,
    projectedYearEndCost: 1520000,
    monthlyData: [
      { month: 'Jan', co2: 1300, cost: 130000 },
      { month: 'Feb', co2: 1250, cost: 125000 },
      { month: 'Mar', co2: 1380, cost: 138000 },
      { month: 'Apr', co2: 1200, cost: 120000 },
      { month: 'May', co2: 1320, cost: 132000 },
      { month: 'Jun', co2: 1280, cost: 128000 },
      { month: 'Jul', co2: 1150, cost: 115000 },
      { month: 'Aug', co2: 1240, cost: 124000 },
      { month: 'Sep', co2: 1300, cost: 130000 },
      { month: 'Oct', co2: 1230, cost: 123000 },
    ],
  },
  v3: {
    vesselId: 'v3',
    year: 2024,
    totalCO2: 3200,
    annualEstimate: 3800,
    eurCost: 320000,
    allowancesPurchased: 3000,
    allowancesRequired: 3800,
    projectedYearEndCost: 380000,
    monthlyData: [
      { month: 'Jan', co2: 320, cost: 32000 },
      { month: 'Feb', co2: 290, cost: 29000 },
      { month: 'Mar', co2: 340, cost: 34000 },
      { month: 'Apr', co2: 310, cost: 31000 },
      { month: 'May', co2: 330, cost: 33000 },
      { month: 'Jun', co2: 300, cost: 30000 },
      { month: 'Jul', co2: 280, cost: 28000 },
      { month: 'Aug', co2: 310, cost: 31000 },
      { month: 'Sep', co2: 320, cost: 32000 },
      { month: 'Oct', co2: 330, cost: 33000 },
    ],
  },
}

// ─── Port Congestion ──────────────────────────────────────────────────────────

export const MOCK_PORT_CONGESTION: PortCongestion[] = [
  {
    portId: 'p1',
    portName: 'Port of Fujairah',
    country: 'UAE',
    congestionLevel: 'high',
    avgWaitingTime: 48,
    vesselsAtAnchor: 24,
    forecast: [
      { date: '2024-11-16', level: 'high' },
      { date: '2024-11-17', level: 'congested' },
      { date: '2024-11-18', level: 'high' },
      { date: '2024-11-19', level: 'medium' },
      { date: '2024-11-20', level: 'medium' },
      { date: '2024-11-21', level: 'low' },
      { date: '2024-11-22', level: 'low' },
    ],
    alerts: ['HIGH CONGESTION — Consider 2-knot speed reduction to save 18 MT fuel'],
  },
  {
    portId: 'p2',
    portName: 'Port of Singapore',
    country: 'Singapore',
    congestionLevel: 'medium',
    avgWaitingTime: 18,
    vesselsAtAnchor: 12,
    forecast: [
      { date: '2024-11-16', level: 'medium' },
      { date: '2024-11-17', level: 'medium' },
      { date: '2024-11-18', level: 'low' },
      { date: '2024-11-19', level: 'low' },
      { date: '2024-11-20', level: 'medium' },
      { date: '2024-11-21', level: 'medium' },
      { date: '2024-11-22', level: 'high' },
    ],
  },
  {
    portId: 'p3',
    portName: 'Port Klang',
    country: 'Malaysia',
    congestionLevel: 'low',
    avgWaitingTime: 6,
    vesselsAtAnchor: 4,
    forecast: [
      { date: '2024-11-16', level: 'low' },
      { date: '2024-11-17', level: 'low' },
      { date: '2024-11-18', level: 'medium' },
      { date: '2024-11-19', level: 'medium' },
      { date: '2024-11-20', level: 'low' },
      { date: '2024-11-21', level: 'low' },
      { date: '2024-11-22', level: 'low' },
    ],
  },
  {
    portId: 'p4',
    portName: 'Port of Rotterdam',
    country: 'Netherlands',
    congestionLevel: 'medium',
    avgWaitingTime: 24,
    vesselsAtAnchor: 18,
    forecast: [
      { date: '2024-11-16', level: 'medium' },
      { date: '2024-11-17', level: 'high' },
      { date: '2024-11-18', level: 'high' },
      { date: '2024-11-19', level: 'medium' },
      { date: '2024-11-20', level: 'low' },
      { date: '2024-11-21', level: 'low' },
      { date: '2024-11-22', level: 'medium' },
    ],
  },
  {
    portId: 'p5',
    portName: 'Port of Houston',
    country: 'USA',
    congestionLevel: 'congested',
    avgWaitingTime: 72,
    vesselsAtAnchor: 35,
    forecast: [
      { date: '2024-11-16', level: 'congested' },
      { date: '2024-11-17', level: 'congested' },
      { date: '2024-11-18', level: 'high' },
      { date: '2024-11-19', level: 'high' },
      { date: '2024-11-20', level: 'medium' },
      { date: '2024-11-21', level: 'medium' },
      { date: '2024-11-22', level: 'low' },
    ],
  },
  {
    portId: 'p6',
    portName: 'Port of Kerteh',
    country: 'Malaysia',
    congestionLevel: 'low',
    avgWaitingTime: 4,
    vesselsAtAnchor: 2,
    forecast: [
      { date: '2024-11-16', level: 'low' },
      { date: '2024-11-17', level: 'low' },
      { date: '2024-11-18', level: 'low' },
      { date: '2024-11-19', level: 'low' },
      { date: '2024-11-20', level: 'medium' },
      { date: '2024-11-21', level: 'low' },
      { date: '2024-11-22', level: 'low' },
    ],
  },
]

// ─── Port Calls ───────────────────────────────────────────────────────────────

export const MOCK_PORT_CALLS: PortCall[] = [
  {
    id: 'pc1',
    vesselId: 'v3',
    portName: 'Port of Fujairah',
    country: 'UAE',
    eta: '2024-11-16T08:00:00Z',
    status: 'arrived',
    berthNumber: 'T-14',
    agentName: 'Fujairah National Shipping Agency',
    agentEmail: 'ops@fnsa-fujairah.ae',
    layTimeAllowed: 36,
    layTimeUsed: 30,
    demurrageRate: 8500,
  },
  {
    id: 'pc2',
    vesselId: 'v1',
    portName: 'Port of Singapore',
    country: 'Singapore',
    eta: '2024-11-20T14:00:00Z',
    status: 'upcoming',
    agentName: 'Pacific Maritime Agency',
    agentEmail: 'arrivals@pacmar-sg.com',
    layTimeAllowed: 48,
    demurrageRate: 12000,
  },
  {
    id: 'pc3',
    vesselId: 'v2',
    portName: 'Port of Fujairah',
    country: 'UAE',
    eta: '2024-11-18T10:00:00Z',
    status: 'upcoming',
    agentName: 'Fujairah National Shipping Agency',
    agentEmail: 'ops@fnsa-fujairah.ae',
    layTimeAllowed: 42,
    demurrageRate: 9000,
  },
]

// ─── Documents ────────────────────────────────────────────────────────────────

export const MOCK_DOCUMENTS: KnowledgeDocument[] = [
  {
    id: 'd1',
    vesselId: 'v1',
    name: 'Main Engine Operation Manual - MAN B&W 6S50MC-C8',
    type: 'manual',
    status: 'indexed',
    uploadedAt: '2024-08-15T10:00:00Z',
    size: 52428800,
    pageCount: 842,
    tags: ['main engine', 'propulsion', 'MAN B&W'],
  },
  {
    id: 'd2',
    vesselId: 'v1',
    name: 'Class Survey Report 2024 - Bureau Veritas',
    type: 'report',
    status: 'indexed',
    uploadedAt: '2024-10-01T14:30:00Z',
    size: 8388608,
    pageCount: 156,
    tags: ['class', 'survey', 'BV'],
  },
  {
    id: 'd3',
    vesselId: 'v1',
    name: 'Previous Defect Reports Q3 2024',
    type: 'report',
    status: 'indexed',
    uploadedAt: '2024-10-15T09:00:00Z',
    size: 2097152,
    pageCount: 48,
    tags: ['defects', 'maintenance'],
  },
  {
    id: 'd4',
    vesselId: 'v1',
    name: 'Turbocharger Maintenance Manual - ABB TPS57',
    type: 'manual',
    status: 'indexed',
    uploadedAt: '2024-09-20T11:00:00Z',
    size: 15728640,
    pageCount: 284,
    tags: ['turbocharger', 'ABB', 'maintenance'],
  },
  {
    id: 'd5',
    vesselId: 'v1',
    name: 'Emergency Procedures Manual v4.2',
    type: 'procedure',
    status: 'indexed',
    uploadedAt: '2024-07-01T08:00:00Z',
    size: 5242880,
    pageCount: 124,
    tags: ['emergency', 'safety', 'procedures'],
  },
]

// ─── SIRE Documents ───────────────────────────────────────────────────────────

export const MOCK_SIRE_DOCS: SireDocument[] = [
  {
    id: 'sd1',
    vesselId: 'v2',
    name: 'Certificate of Fitness',
    type: 'certificate',
    expiryDate: '2025-06-15',
    status: 'valid',
    daysToExpiry: 212,
    uploadedAt: '2024-06-15T10:00:00Z',
  },
  {
    id: 'sd2',
    vesselId: 'v2',
    name: 'Pollution Prevention Certificate (IOPP)',
    type: 'certificate',
    expiryDate: '2024-12-08',
    status: 'expiring_soon',
    daysToExpiry: 23,
    uploadedAt: '2024-12-08T10:00:00Z',
  },
  {
    id: 'sd3',
    vesselId: 'v2',
    name: 'Document of Compliance (DOC)',
    type: 'certificate',
    expiryDate: '2024-10-31',
    status: 'expired',
    daysToExpiry: -15,
    uploadedAt: '2021-10-31T10:00:00Z',
  },
  {
    id: 'sd4',
    vesselId: 'v2',
    name: 'ISPS Security Certificate',
    type: 'certificate',
    expiryDate: '2025-03-20',
    status: 'valid',
    daysToExpiry: 125,
    uploadedAt: '2020-03-20T10:00:00Z',
  },
  {
    id: 'sd5',
    vesselId: 'v2',
    name: 'Minimum Safe Manning Certificate',
    type: 'certificate',
    expiryDate: '2025-09-01',
    status: 'valid',
    daysToExpiry: 290,
    uploadedAt: '2022-09-01T10:00:00Z',
  },
  {
    id: 'sd6',
    vesselId: 'v2',
    name: 'Emergency Response Plan',
    type: 'procedure',
    expiryDate: '2024-11-05',
    status: 'expired',
    daysToExpiry: -10,
    uploadedAt: '2023-11-05T10:00:00Z',
  },
]

// ─── SIRE Findings ────────────────────────────────────────────────────────────

export const MOCK_SIRE_FINDINGS: SireFinding[] = [
  {
    id: 'sf1',
    vesselId: 'v2',
    inspectionDate: '2024-08-15',
    chapter: 4,
    chapterTitle: 'Pollution Prevention',
    finding: 'Oil Water Separator alarm bypass switch found in bypass position during routine inspection',
    severity: 'major',
    status: 'in_progress',
    dueDate: '2024-11-30',
    correctiveAction: 'Alarm system repaired. Crew training conducted. Monthly testing log implemented.',
  },
  {
    id: 'sf2',
    vesselId: 'v2',
    inspectionDate: '2024-08-15',
    chapter: 8,
    chapterTitle: 'Machinery',
    finding: 'Main engine lube oil analysis not conducted within required 3-month interval',
    severity: 'deficiency',
    status: 'open',
    dueDate: '2024-12-15',
  },
  {
    id: 'sf3',
    vesselId: 'v2',
    inspectionDate: '2024-08-15',
    chapter: 2,
    chapterTitle: 'Navigation',
    finding: 'ECDIS system backup not tested within required 12-month period',
    severity: 'deficiency',
    status: 'closed',
    dueDate: '2024-10-15',
    closedAt: '2024-10-10',
    correctiveAction: 'ECDIS backup tested and certified. Testing schedule established.',
  },
  {
    id: 'sf4',
    vesselId: 'v2',
    inspectionDate: '2024-08-15',
    chapter: 7,
    chapterTitle: 'Safety Management',
    finding: 'Fire drill records incomplete for Q2 2024',
    severity: 'observation',
    status: 'closed',
    dueDate: '2024-09-15',
    closedAt: '2024-09-08',
  },
]

// ─── SIRE Chapter Scores ──────────────────────────────────────────────────────

export const MOCK_SIRE_CHAPTERS: Record<string, SireChapterScore[]> = {
  v1: [
    { chapter: 1, title: 'Management', score: 88, maxScore: 100, findings: 1, status: 'green' },
    { chapter: 2, title: 'Navigation', score: 85, maxScore: 100, findings: 2, status: 'green' },
    { chapter: 3, title: 'Mooring', score: 90, maxScore: 100, findings: 0, status: 'green' },
    { chapter: 4, title: 'Pollution Prevention', score: 82, maxScore: 100, findings: 1, status: 'green' },
    { chapter: 5, title: 'Cargo Operations', score: 87, maxScore: 100, findings: 1, status: 'green' },
    { chapter: 6, title: 'Crew', score: 92, maxScore: 100, findings: 0, status: 'green' },
    { chapter: 7, title: 'Safety Management', score: 86, maxScore: 100, findings: 1, status: 'green' },
    { chapter: 8, title: 'Machinery', score: 78, maxScore: 100, findings: 2, status: 'amber' },
  ],
  v2: [
    { chapter: 1, title: 'Management', score: 72, maxScore: 100, findings: 2, status: 'amber' },
    { chapter: 2, title: 'Navigation', score: 68, maxScore: 100, findings: 3, status: 'amber' },
    { chapter: 3, title: 'Mooring', score: 75, maxScore: 100, findings: 1, status: 'amber' },
    { chapter: 4, title: 'Pollution Prevention', score: 45, maxScore: 100, findings: 5, status: 'red' },
    { chapter: 5, title: 'Cargo Operations', score: 70, maxScore: 100, findings: 2, status: 'amber' },
    { chapter: 6, title: 'Crew', score: 78, maxScore: 100, findings: 1, status: 'amber' },
    { chapter: 7, title: 'Safety Management', score: 65, maxScore: 100, findings: 3, status: 'amber' },
    { chapter: 8, title: 'Machinery', score: 52, maxScore: 100, findings: 4, status: 'red' },
  ],
  v3: [
    { chapter: 1, title: 'Management', score: 82, maxScore: 100, findings: 1, status: 'green' },
    { chapter: 2, title: 'Navigation', score: 79, maxScore: 100, findings: 2, status: 'amber' },
    { chapter: 3, title: 'Mooring', score: 85, maxScore: 100, findings: 0, status: 'green' },
    { chapter: 4, title: 'Pollution Prevention', score: 80, maxScore: 100, findings: 1, status: 'green' },
    { chapter: 5, title: 'Cargo Operations', score: 83, maxScore: 100, findings: 1, status: 'green' },
    { chapter: 6, title: 'Crew', score: 88, maxScore: 100, findings: 0, status: 'green' },
    { chapter: 7, title: 'Safety Management', score: 81, maxScore: 100, findings: 1, status: 'green' },
    { chapter: 8, title: 'Machinery', score: 76, maxScore: 100, findings: 2, status: 'amber' },
  ],
}

// ─── Voyage History ───────────────────────────────────────────────────────────

export const MOCK_VOYAGE_HISTORY: VoyageHistoryRecord[] = [
  { id: 'vh1', vesselId: 'v1', route: 'Kerteh → Singapore', departureDate: '2024-11-01', arrivalDate: '2024-11-03', plannedFuel: 280, actualFuel: 262, savings: 18, ciiImpact: -0.15 },
  { id: 'vh2', vesselId: 'v1', route: 'Singapore → Labuan', departureDate: '2024-10-20', arrivalDate: '2024-10-22', plannedFuel: 195, actualFuel: 188, savings: 7, ciiImpact: -0.08 },
  { id: 'vh3', vesselId: 'v1', route: 'Labuan → Kerteh', departureDate: '2024-10-10', arrivalDate: '2024-10-13', plannedFuel: 240, actualFuel: 251, savings: -11, ciiImpact: 0.12 },
  { id: 'vh4', vesselId: 'v1', route: 'Kerteh → Fujairah', departureDate: '2024-09-25', arrivalDate: '2024-10-04', plannedFuel: 820, actualFuel: 798, savings: 22, ciiImpact: -0.18 },
  { id: 'vh5', vesselId: 'v1', route: 'Fujairah → Singapore', departureDate: '2024-09-10', arrivalDate: '2024-09-18', plannedFuel: 680, actualFuel: 661, savings: 19, ciiImpact: -0.16 },
]
